import {
  GLOBAL_REFERENCE_SOURCE_PROTOCOL_VERSION,
  type GlobalReferenceSourceDescriptor,
} from "@markorbit/contracts";
import type { CreateSourceInput, SourceRepository } from "./index";

const descriptor = (
  input: Omit<GlobalReferenceSourceDescriptor, "protocolVersion" | "objectType" | "sourceType">,
): GlobalReferenceSourceDescriptor => ({
  protocolVersion: GLOBAL_REFERENCE_SOURCE_PROTOCOL_VERSION,
  objectType: "GLOBAL_REFERENCE_SOURCE",
  sourceType: "WEB",
  ...input,
});

export const GLOBAL_REFERENCE_SOURCES: readonly GlobalReferenceSourceDescriptor[] = [
  descriptor({
    id: "fmprc-country-profiles",
    name: "Ministry of Foreign Affairs of China — Country Profiles",
    canonicalUri: "https://www.fmprc.gov.cn/web/gjhdq_676201/gj_676203/yz_676205/",
    category: "OFFICIAL_AUTHORITY",
    authorityLevel: "PRIMARY_OFFICIAL",
    sourceRole: "COUNTRY_CONTEXT",
    authorityTier: "A",
    jurisdictionScope: "MULTI_JURISDICTION",
    languages: ["zh-CN"],
    contentDomains: ["COUNTRY_PROFILE"],
    intendedUses: ["COUNTRY_PROFILE"],
    factEligibility: "PRIMARY",
    changeSignalEligible: false,
    verification: { policy: "NOT_REQUIRED" },
    contentReusePolicy: "FACT_EXTRACTION_WITH_PROVENANCE",
    freshnessPolicy: "MONTHLY",
    acquisition: {
      mode: "WEB_CRAWL",
      renderJavascriptHint: false,
      fetchAttachmentsHint: false,
      expectedArtifactKinds: ["HTML", "MARKDOWN"],
    },
    tags: ["country-context", "china-official"],
  }),
  descriptor({
    id: "belt-road-investment-guides",
    name: "Belt and Road Portal — Investment Guides",
    canonicalUri: "https://www.yidaiyilu.gov.cn/list/c/xdzzn",
    category: "OFFICIAL_GUIDANCE",
    authorityLevel: "SECONDARY_OFFICIAL",
    sourceRole: "INVESTMENT_GUIDE",
    authorityTier: "A",
    jurisdictionScope: "MULTI_JURISDICTION",
    languages: ["zh-CN"],
    contentDomains: ["COUNTRY_PROFILE", "INVESTMENT_ENVIRONMENT"],
    intendedUses: ["COUNTRY_PROFILE"],
    factEligibility: "PRIMARY",
    changeSignalEligible: false,
    verification: { policy: "CONDITIONAL" },
    contentReusePolicy: "FACT_EXTRACTION_WITH_PROVENANCE",
    freshnessPolicy: "MONTHLY",
    acquisition: {
      mode: "WEB_CRAWL",
      renderJavascriptHint: true,
      fetchAttachmentsHint: true,
      expectedArtifactKinds: ["HTML", "MARKDOWN", "PDF"],
    },
    tags: ["investment-guide", "china-official"],
  }),
  descriptor({
    id: "un-world-population-prospects",
    name: "United Nations — World Population Prospects",
    canonicalUri: "https://population.un.org/wpp/",
    category: "RESEARCH",
    authorityLevel: "PRIMARY_OFFICIAL",
    sourceRole: "COUNTRY_STATISTICS",
    authorityTier: "A",
    jurisdictionScope: "GLOBAL",
    languages: ["en"],
    contentDomains: ["DEMOGRAPHICS"],
    intendedUses: ["COUNTRY_PROFILE"],
    factEligibility: "PRIMARY",
    changeSignalEligible: false,
    verification: { policy: "NOT_REQUIRED" },
    contentReusePolicy: "FACT_EXTRACTION_WITH_PROVENANCE",
    freshnessPolicy: "ANNUAL",
    acquisition: {
      mode: "API_OR_STRUCTURED",
      renderJavascriptHint: true,
      fetchAttachmentsHint: true,
      expectedArtifactKinds: ["HTML", "CSV", "XLSX", "JSON"],
    },
    tags: ["population", "un", "primary-statistics"],
  }),
  descriptor({
    id: "world-population-review-countries",
    name: "World Population Review — Countries",
    canonicalUri: "https://worldpopulationreview.com/countries",
    category: "RESEARCH",
    authorityLevel: "INDUSTRY",
    sourceRole: "COUNTRY_STATISTICS",
    authorityTier: "B",
    jurisdictionScope: "GLOBAL",
    languages: ["en"],
    contentDomains: ["DEMOGRAPHICS"],
    intendedUses: ["COUNTRY_PROFILE"],
    factEligibility: "SECONDARY",
    changeSignalEligible: false,
    verification: {
      policy: "REQUIRED",
      verifyAgainstSourceIds: ["un-world-population-prospects"],
    },
    contentReusePolicy: "FACT_EXTRACTION_WITH_PROVENANCE",
    freshnessPolicy: "MONTHLY",
    acquisition: {
      mode: "WEB_CRAWL",
      renderJavascriptHint: true,
      fetchAttachmentsHint: false,
      expectedArtifactKinds: ["HTML", "MARKDOWN"],
    },
    tags: ["population", "secondary-statistics"],
    notes: "Convenient secondary population view; population facts should be verified against UN WPP.",
  }),
  descriptor({
    id: "international-property-rights-index-countries",
    name: "International Property Rights Index — Countries",
    canonicalUri: "https://internationalpropertyrightsindex.org/countries",
    category: "RESEARCH",
    authorityLevel: "PROFESSIONAL",
    sourceRole: "PROPERTY_RIGHTS_INDEX",
    authorityTier: "B",
    jurisdictionScope: "GLOBAL",
    languages: ["en"],
    contentDomains: ["PROPERTY_RIGHTS", "TRADEMARK_PRACTICE"],
    intendedUses: ["COUNTRY_PROFILE", "TRADEMARK_PROFILE"],
    factEligibility: "SECONDARY",
    changeSignalEligible: false,
    verification: { policy: "CONDITIONAL" },
    contentReusePolicy: "FACT_EXTRACTION_WITH_PROVENANCE",
    freshnessPolicy: "ANNUAL",
    acquisition: {
      mode: "WEB_CRAWL",
      renderJavascriptHint: true,
      fetchAttachmentsHint: true,
      expectedArtifactKinds: ["HTML", "MARKDOWN", "PDF"],
    },
    tags: ["property-rights", "ip-protection-index"],
    notes: "Treat as a property-rights/IP-protection signal, not as a general country competitiveness index.",
  }),
  descriptor({
    id: "country-index-country-surveys",
    name: "Country Index — Trademark Country Surveys",
    canonicalUri: "https://country-index.com/country_surveys.aspx",
    category: "RESEARCH",
    authorityLevel: "PROFESSIONAL",
    sourceRole: "TM_PRACTICE_GUIDE",
    authorityTier: "B_PLUS",
    jurisdictionScope: "GLOBAL",
    languages: ["en"],
    contentDomains: ["TRADEMARK_PRACTICE", "TRADEMARK_LAW"],
    intendedUses: ["TRADEMARK_PROFILE"],
    factEligibility: "SECONDARY",
    changeSignalEligible: false,
    verification: {
      policy: "REQUIRED",
      verifyAgainstJurisdictionOfficialSource: true,
    },
    contentReusePolicy: "FACT_EXTRACTION_WITH_PROVENANCE",
    freshnessPolicy: "MONTHLY",
    acquisition: {
      mode: "WEB_CRAWL",
      renderJavascriptHint: false,
      fetchAttachmentsHint: false,
      expectedArtifactKinds: ["HTML", "MARKDOWN"],
    },
    tags: ["trademark-country-survey", "professional-secondary"],
  }),
  descriptor({
    id: "country-index-newsletter",
    name: "Country Index — Trademark Newsletter",
    canonicalUri: "https://country-index.com/newsletter.aspx",
    category: "NEWS",
    authorityLevel: "PROFESSIONAL",
    sourceRole: "TM_CHANGE_SIGNAL",
    authorityTier: "B_PLUS",
    jurisdictionScope: "GLOBAL",
    languages: ["en"],
    contentDomains: ["TRADEMARK_CHANGE", "TRADEMARK_PRACTICE"],
    intendedUses: ["CHANGE_SIGNAL", "TRADEMARK_PROFILE"],
    factEligibility: "SUPPORTING_ONLY",
    changeSignalEligible: true,
    verification: {
      policy: "REQUIRED",
      verifyAgainstJurisdictionOfficialSource: true,
    },
    contentReusePolicy: "FACT_EXTRACTION_WITH_PROVENANCE",
    freshnessPolicy: "BIWEEKLY",
    acquisition: {
      mode: "WEB_CRAWL",
      renderJavascriptHint: false,
      fetchAttachmentsHint: false,
      expectedArtifactKinds: ["HTML", "MARKDOWN"],
    },
    tags: ["trademark-news", "change-signal", "professional-secondary"],
    notes: "Use as a change detector; do not overwrite official jurisdiction facts without primary verification.",
  }),
  descriptor({
    id: "wipo-country-ip-profiles",
    name: "WIPO — Country IP Profiles",
    canonicalUri: "https://www.wipo.int/directory/en/",
    category: "OFFICIAL_AUTHORITY",
    authorityLevel: "PRIMARY_OFFICIAL",
    sourceRole: "IP_AUTHORITY_REFERENCE",
    authorityTier: "A_PLUS",
    jurisdictionScope: "GLOBAL",
    languages: ["en"],
    contentDomains: ["COUNTRY_PROFILE", "TRADEMARK_PRACTICE"],
    intendedUses: ["COUNTRY_PROFILE", "TRADEMARK_PROFILE"],
    factEligibility: "AUTHORITATIVE_AGGREGATOR",
    changeSignalEligible: true,
    verification: { policy: "CONDITIONAL" },
    contentReusePolicy: "FACT_EXTRACTION_WITH_PROVENANCE",
    freshnessPolicy: "MONTHLY",
    acquisition: {
      mode: "WEB_CRAWL",
      renderJavascriptHint: true,
      fetchAttachmentsHint: false,
      expectedArtifactKinds: ["HTML", "MARKDOWN"],
    },
    tags: ["wipo", "ip-office-directory", "authority-reference"],
  }),
  descriptor({
    id: "wipo-ip-advantage",
    name: "WIPO — IP Advantage Case Studies",
    canonicalUri: "https://www.wipo.int/en/web/ip-advantage/search",
    category: "OFFICIAL_GUIDANCE",
    authorityLevel: "PRIMARY_OFFICIAL",
    sourceRole: "IP_CASE_STUDY",
    authorityTier: "A",
    jurisdictionScope: "GLOBAL",
    languages: ["en"],
    contentDomains: ["IP_CASES"],
    intendedUses: ["CASE_LIBRARY", "CONTENT_IDEATION"],
    factEligibility: "AUTHORITATIVE_AGGREGATOR",
    changeSignalEligible: false,
    verification: { policy: "CONDITIONAL" },
    contentReusePolicy: "FACT_EXTRACTION_WITH_PROVENANCE",
    freshnessPolicy: "MONTHLY",
    acquisition: {
      mode: "WEB_CRAWL",
      renderJavascriptHint: true,
      fetchAttachmentsHint: false,
      expectedArtifactKinds: ["HTML", "MARKDOWN"],
    },
    tags: ["wipo", "ip-cases", "case-library"],
  }),
  descriptor({
    id: "wipo-lex",
    name: "WIPO Lex",
    canonicalUri: "https://www.wipo.int/wipolex/en/index.html",
    category: "OFFICIAL_AUTHORITY",
    authorityLevel: "PRIMARY_OFFICIAL",
    sourceRole: "IP_LEGAL_SOURCE",
    authorityTier: "A_PLUS",
    jurisdictionScope: "GLOBAL",
    languages: ["en"],
    contentDomains: ["TRADEMARK_LAW"],
    intendedUses: ["TRADEMARK_PROFILE", "CHANGE_SIGNAL"],
    factEligibility: "AUTHORITATIVE_AGGREGATOR",
    changeSignalEligible: true,
    verification: { policy: "CONDITIONAL" },
    contentReusePolicy: "FACT_EXTRACTION_WITH_PROVENANCE",
    freshnessPolicy: "WEEKLY",
    acquisition: {
      mode: "MIXED",
      renderJavascriptHint: true,
      fetchAttachmentsHint: true,
      expectedArtifactKinds: ["HTML", "MARKDOWN", "PDF"],
    },
    tags: ["wipo", "laws", "regulations", "legal-source"],
  }),
  descriptor({
    id: "iclg-trade-marks",
    name: "ICLG — Trade Marks Laws and Regulations",
    canonicalUri: "https://iclg.com/practice-areas/trade-marks-laws-and-regulations",
    category: "RESEARCH",
    authorityLevel: "PROFESSIONAL",
    sourceRole: "TM_EXPERT_GUIDE",
    authorityTier: "B_PLUS",
    jurisdictionScope: "MULTI_JURISDICTION",
    languages: ["en"],
    contentDomains: ["TRADEMARK_PRACTICE", "TRADEMARK_LAW"],
    intendedUses: ["TRADEMARK_PROFILE"],
    factEligibility: "SECONDARY",
    changeSignalEligible: true,
    verification: {
      policy: "REQUIRED",
      verifyAgainstJurisdictionOfficialSource: true,
    },
    contentReusePolicy: "FACT_EXTRACTION_WITH_PROVENANCE",
    freshnessPolicy: "ANNUAL",
    acquisition: {
      mode: "WEB_CRAWL",
      renderJavascriptHint: false,
      fetchAttachmentsHint: false,
      expectedArtifactKinds: ["HTML", "MARKDOWN"],
    },
    tags: ["expert-guide", "lawyer-authored", "professional-secondary"],
  }),
  descriptor({
    id: "legalzoom-trademarks",
    name: "LegalZoom — Trademark Articles",
    canonicalUri: "https://www.legalzoom.com/articles/categories/trademarks",
    category: "OTHER",
    authorityLevel: "INDUSTRY",
    sourceRole: "CONTENT_MARKETING_REFERENCE",
    authorityTier: "C",
    jurisdictionScope: "MULTI_JURISDICTION",
    languages: ["en"],
    contentDomains: ["CONTENT_IDEATION"],
    intendedUses: ["CONTENT_IDEATION"],
    factEligibility: "NONE",
    changeSignalEligible: false,
    verification: { policy: "REQUIRED" },
    contentReusePolicy: "STRUCTURE_AND_TOPIC_ONLY",
    freshnessPolicy: "MONTHLY",
    acquisition: {
      mode: "WEB_CRAWL",
      renderJavascriptHint: true,
      fetchAttachmentsHint: false,
      expectedArtifactKinds: ["HTML", "MARKDOWN"],
    },
    tags: ["content-reference", "topic-ideation", "no-legal-fact-promotion"],
  }),
  descriptor({
    id: "igerent-global-trademark-services",
    name: "iGERENT — Global Trademark Services and Pricing",
    canonicalUri: "https://igerent.com/",
    category: "LAW_FIRM",
    authorityLevel: "PROFESSIONAL",
    sourceRole: "COMPETITOR_BENCHMARK",
    authorityTier: "C_PLUS",
    jurisdictionScope: "GLOBAL",
    languages: ["en"],
    contentDomains: ["PROVIDER_PRICING", "TRADEMARK_PRACTICE"],
    intendedUses: ["PROVIDER_BENCHMARK"],
    factEligibility: "NONE",
    changeSignalEligible: false,
    verification: { policy: "NOT_REQUIRED" },
    contentReusePolicy: "BENCHMARK_ONLY",
    freshnessPolicy: "MONTHLY",
    acquisition: {
      mode: "WEB_CRAWL",
      renderJavascriptHint: true,
      fetchAttachmentsHint: false,
      expectedArtifactKinds: ["HTML", "MARKDOWN"],
    },
    tags: ["competitor", "provider-pricing", "benchmark"],
    notes: "Provider-stated service/pricing facts are usable for benchmarking; legal practice claims are not promoted as legal facts.",
  }),
  descriptor({
    id: "simonianip-trademarks",
    name: "Simonian IP — Trademark Country Information",
    canonicalUri: "https://www.simonianip.com/trademarks/index.php",
    category: "LAW_FIRM",
    authorityLevel: "PROFESSIONAL",
    sourceRole: "LEGACY_REFERENCE",
    authorityTier: "D",
    jurisdictionScope: "GLOBAL",
    languages: ["en"],
    contentDomains: ["TRADEMARK_PRACTICE"],
    intendedUses: ["LEGACY_CROSSCHECK"],
    factEligibility: "SUPPORTING_ONLY",
    changeSignalEligible: false,
    verification: {
      policy: "REQUIRED",
      verifyAgainstJurisdictionOfficialSource: true,
    },
    contentReusePolicy: "LEGACY_CROSSCHECK_ONLY",
    freshnessPolicy: "LOW_FREQUENCY",
    acquisition: {
      mode: "WEB_CRAWL",
      renderJavascriptHint: false,
      fetchAttachmentsHint: false,
      expectedArtifactKinds: ["HTML", "MARKDOWN"],
    },
    tags: ["legacy", "trademark-country-info", "crosscheck-only"],
  }),
  descriptor({
    id: "proxario-countries",
    name: "Proxario — Trademark Country Information",
    canonicalUri: "https://www.proxario.com/countries.html",
    category: "LAW_FIRM",
    authorityLevel: "PROFESSIONAL",
    sourceRole: "LEGACY_REFERENCE",
    authorityTier: "D",
    jurisdictionScope: "GLOBAL",
    languages: ["en"],
    contentDomains: ["TRADEMARK_PRACTICE"],
    intendedUses: ["LEGACY_CROSSCHECK"],
    factEligibility: "SUPPORTING_ONLY",
    changeSignalEligible: false,
    verification: {
      policy: "REQUIRED",
      verifyAgainstJurisdictionOfficialSource: true,
    },
    contentReusePolicy: "LEGACY_CROSSCHECK_ONLY",
    freshnessPolicy: "LOW_FREQUENCY",
    acquisition: {
      mode: "WEB_CRAWL",
      renderJavascriptHint: false,
      fetchAttachmentsHint: false,
      expectedArtifactKinds: ["HTML", "MARKDOWN"],
    },
    tags: ["legacy", "trademark-country-info", "crosscheck-only"],
  }),
] as const;

export function getGlobalReferenceSource(id: string): GlobalReferenceSourceDescriptor | null {
  return GLOBAL_REFERENCE_SOURCES.find((source) => source.id === id) ?? null;
}

export function listGlobalReferenceSources(input?: {
  role?: GlobalReferenceSourceDescriptor["sourceRole"];
  intendedUse?: GlobalReferenceSourceDescriptor["intendedUses"][number];
}): GlobalReferenceSourceDescriptor[] {
  return GLOBAL_REFERENCE_SOURCES.filter((source) => {
    if (input?.role && source.sourceRole !== input.role) return false;
    if (input?.intendedUse && !source.intendedUses.includes(input.intendedUse)) return false;
    return true;
  });
}

export function toReferenceSourceCreateInput(
  source: GlobalReferenceSourceDescriptor,
): CreateSourceInput {
  const verificationSourceIds = source.verification.verifyAgainstSourceIds;

  return {
    name: source.name,
    slug: source.id,
    sourceType: source.sourceType,
    category: source.category,
    authorityLevel: source.authorityLevel,
    status: "ACTIVE",
    jurisdictions: [source.jurisdictionScope === "GLOBAL" ? "GLOBAL" : "MULTI"],
    languages: source.languages,
    connector: { connectorId: "crawl4ai-web", version: "1.0.0" },
    connectorConfig: {
      renderJavascript: source.acquisition.renderJavascriptHint,
      maxDepth: 1,
    },
    canonicalUri: source.canonicalUri,
    entrypoints: [{ uri: source.canonicalUri, label: source.name }],
    tags: [
      "global-reference-source",
      `reference-role:${source.sourceRole.toLowerCase()}`,
      ...source.tags,
    ],
    extensions: {
      "x-markorbit-reference-protocol-version": source.protocolVersion,
      "x-markorbit-reference-role": source.sourceRole,
      "x-markorbit-reference-authority-tier": source.authorityTier,
      "x-markorbit-reference-content-domains": source.contentDomains,
      "x-markorbit-reference-intended-uses": source.intendedUses,
      "x-markorbit-reference-fact-eligibility": source.factEligibility,
      "x-markorbit-reference-change-signal-eligible": source.changeSignalEligible,
      "x-markorbit-reference-verification-policy": source.verification.policy,
      "x-markorbit-reference-verify-official-source":
        source.verification.verifyAgainstJurisdictionOfficialSource ?? false,
      ...(verificationSourceIds
        ? { "x-markorbit-reference-verification-source-ids": verificationSourceIds }
        : {}),
      "x-markorbit-reference-content-reuse-policy": source.contentReusePolicy,
      "x-markorbit-reference-freshness-policy": source.freshnessPolicy,
    },
  };
}

export function registerGlobalReferenceSources(
  repository: Pick<SourceRepository, "create" | "list">,
): { created: number; existing: number } {
  let created = 0;
  let existing = 0;

  for (const source of GLOBAL_REFERENCE_SOURCES) {
    const match = repository.list({ q: source.id, limit: 100 }).items.some(
      (registered) => registered.slug === source.id,
    );

    if (match) {
      existing += 1;
      continue;
    }

    repository.create(toReferenceSourceCreateInput(source));
    created += 1;
  }

  return { created, existing };
}
